version: '2'
services:
  pg_fts:
    image: postgres:11.2
    container_name: pg_fts
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    - ./install_extensions.sh:/docker-entrypoint-initdb.d/install_extensions.sh
    - ./data:/data
    ports:
      - 5454:5432